## 웹 API의 이해
- API란 Application Programming Interface 의 약자로 컴퓨팅 처리를 쉽게 해주는 기능을 말합니다.
    - 조금 더 설명하면, 두 소프트웨어가 서로 통신할 수 있도록 연결 시켜주는 기능이고,
    - 한 마디로 줄이면, API는 기능입니다.
    - 즉, 우리가 브라우저를 통해 서버에게 정보를 요청한 것이 api를 사용한 것

### 웹 API의 데이터 획득 과정
    - 요청과 응답
    - 요청: reqeust - python의 경우 requests 라이브러리
        - url 만들기(경로 추가, 매개 변수 추가)
    - 응답: response - html, json


### 웹 API의 인증 방식
     - key를 사용하지 않는 경우 - url = 'https://api.agify.io/?name=jun', url = 'http://api.open-notify.org/iss-now.json'
     - key(a.k.a api_key)를 사용하는 경우


### 응답 데이터의 형식 및 처리
    - html, json, xml

#### JSON 형식의 데이터 처리

* 파이썬 딕셔너리를 Json으로 변환: json.dump()
* Json을 파이썬 딕셔너리로 변환: json.load()

## 요청을 위한 형식 만들기(url, 경로 추가, 매개 변수 추가)

In [1]:
import requests

In [7]:
base_url = 'https://api.github.com/'

sub_url = 'events'

url = base_url + sub_url
requests.get(url).text

'[{"id":"23127773670","type":"IssueCommentEvent","actor":{"id":24557394,"login":"YongxueHong","display_login":"YongxueHong","gravatar_id":"","url":"https://api.github.com/users/YongxueHong","avatar_url":"https://avatars.githubusercontent.com/u/24557394?"},"repo":{"id":36371959,"name":"avocado-framework/avocado-vt","url":"https://api.github.com/repos/avocado-framework/avocado-vt"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/avocado-framework/avocado-vt/issues/3416","repository_url":"https://api.github.com/repos/avocado-framework/avocado-vt","labels_url":"https://api.github.com/repos/avocado-framework/avocado-vt/issues/3416/labels{/name}","comments_url":"https://api.github.com/repos/avocado-framework/avocado-vt/issues/3416/comments","events_url":"https://api.github.com/repos/avocado-framework/avocado-vt/issues/3416/events","html_url":"https://github.com/avocado-framework/avocado-vt/pull/3416","id":1253251021,"node_id":"PR_kwDOAir99844tcA4","number":3416,"ti

In [17]:
import requests
from bs4 import BeautifulSoup as bs
base_url = 'https://news.google.com/'
search_url = 'search?1='+'파이썬'+'hl=ko&gl=KR&ceid=KR%3Ako'

url = base_url + search_url
requests.get(url).text


'<!doctype html><html lang="en" dir="ltr"><head><base href="https://news.google.com/"><meta name="referrer" content="origin"><link rel="canonical" href="https://news.google.com/topstories"><meta name="viewport" content="width=device-width,initial-scale=1,minimal-ui"><meta name="google-site-verification" content="AcBy5YFny2HQgVUCR18tO5YUTf6MpVlcJqGTd-a9-SI"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="application-name" content="News"><meta name="apple-mobile-web-app-title" content="News"><meta name="apple-mobile-web-app-status-bar-style" content="black"><meta name="theme-color" content="white"><meta name="msapplication-tap-highlight" content="no"><link rel="shortcut icon" href="https://lh3.googleusercontent.com/-DR60l-K8vnyi99NZovm9HlXyZwQ85GMDxiwJWzoasZYCUrPuUM_P_4Rb7ei03j-0nRs0c4F=w16" sizes="16x16"><link rel="shortcut icon" href="https://lh3.googleusercontent.com/-DR60l-K8vnyi99NZovm9HlXyZwQ85GMDxiwJWzoasZYCUrPu

## API 키를 사용하지 않고 데이터 가져오기
### 국제 우주 정거장의 정보 가져오기(iss-now)

In [51]:
import requests
import json

url = 'http://api.open-notify.org/iss-now.json'
result = requests.get(url).text




AttributeError: module 'time' has no attribute 'text'

In [47]:
dict1 = json.loads(result)
dict1

{'timestamp': 1658995501,
 'message': 'success',
 'iss_position': {'latitude': '51.4625', 'longitude': '161.6786'}}

In [48]:
latitude = float(dict1.get('iss_position').get('latitude'))
longitude = float(dict1.get('iss_position').get('longitude'))

print(latitude, longitude)

51.4625 161.6786


In [49]:
latitude = float(dict1['iss_position']['latitude'])
longitude = float(dict1['iss_position']['longitude'])
print(latitude, longitude)

51.4625 161.6786


* 국제 우주정거장의 위치 정보를 10초마다 갱신하는 코드

In [54]:
import requests
import json
import time

url = 'http://api.open-notify.org/iss-now.json'
for k in range(5):
    result = requests.get(url).text
    dict1 = json.loads(result)
    latitude = float(dict1['iss_position']['latitude'])
    longitude = float(dict1['iss_position']['longitude'])
    print(f'위도 : {latitude}, 경도 : {longitude}')
    time.sleep(10)

위도 : 48.9437, 경도 : 179.3473
위도 : 48.7171, 경도 : -179.7208
위도 : 48.4823, 경도 : -178.7977
위도 : 48.2512, 경도 : -177.9272
위도 : 48.0009, 경도 : -177.022


### agify api 

In [68]:
import requests
inp = input()
name = f'name={inp}'
url = f'https://api.agify.io/?{name}'
result = requests.get(url).json()
result

1236


{'name': '1236', 'age': None, 'count': 0}

### lotto  api

In [81]:
url = 'https://www.dhlottery.co.kr/common.do?method=getLottoNumber&drwNo=1021'

result = requests.get(url).json()
print(result)
li=[result['drwtNo1'],result['drwtNo2'],result['drwtNo3'],result['drwtNo4'],result['drwtNo5'],result['drwtNo6']]
print(li)

{'totSellamnt': 101960162000, 'returnValue': 'success', 'drwNoDate': '2022-06-25', 'firstWinamnt': 2108962250, 'drwtNo6': 45, 'drwtNo4': 24, 'firstPrzwnerCo': 12, 'drwtNo5': 29, 'bnusNo': 16, 'firstAccumamnt': 25307547000, 'drwNo': 1021, 'drwtNo2': 15, 'drwtNo3': 17, 'drwtNo1': 12}
[12, 15, 17, 24, 29, 45]


## key를 사용하여 데이터를 요청하는 경우
- 대부분의 api server 에서 요구하는 방식
- 공공 데이터 포털
- 네이버 개발자 센터, 카카오 개발자 그룹, etc


* TMDB API 기본 사용법과 키 발급 받는 방법
 - https://www.themoviedb.org/signup?language=ko


### 응답 데이터의 형식 및 처리
    - html, json, xml

#### JSON 형식의 데이터 처리

* 파이썬 딕셔너리를 Json으로 변환: json.dump()
* Json을 파이썬 딕셔너리로 변환: json.load()

2020년 3월 서울 지하철역 유동인구 정보를 분석하고 지도에 표시하려고 합니다.
google map platform(https://developers.google.com/maps/documentation/geocoding/overview)에서 제공하는 api를 사용하여 "동대문역"의 지리 정보를 얻어 json 변수에 할당하였습니다.

In [95]:
json = {'results': [{'address_components': [{'long_name': '２８８', 'short_name': '２８８', 'types': ['premise']}, {'long_name': '종로', 'short_name': '종로', 'types': ['political', 'sublocality', 'sublocality_level_4']}, {'long_name': '종로6가', 'short_name': '종로6가', 'types': ['political', 'sublocality', 'sublocality_level_2']}, {'long_name': '종로구', 'short_name': '종로구', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}, {'long_name': '110-126', 'short_name': '110-126', 'types': ['postal_code']}], 'formatted_address': '대한민국 서울특별시 종로구 종로6가 종로 288', 'geometry': {'location': {'lat': 37.5711389, 'lng': 127.0095452}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 37.5724878802915, 'lng': 127.0108941802915}, 'southwest': {'lat': 37.5697899197085, 'lng': 127.0081962197085}}}, 'place_id': 'ChIJm6x0HTujfDURbf9iX8DtJ2A', 'types': ['establishment', 'point_of_interest', 'tourist_attraction']}], 'status': 'OK'}
json

{'results': [{'address_components': [{'long_name': '２８８',
     'short_name': '２８８',
     'types': ['premise']},
    {'long_name': '종로',
     'short_name': '종로',
     'types': ['political', 'sublocality', 'sublocality_level_4']},
    {'long_name': '종로6가',
     'short_name': '종로6가',
     'types': ['political', 'sublocality', 'sublocality_level_2']},
    {'long_name': '종로구',
     'short_name': '종로구',
     'types': ['political', 'sublocality', 'sublocality_level_1']},
    {'long_name': '서울특별시',
     'short_name': '서울특별시',
     'types': ['administrative_area_level_1', 'political']},
    {'long_name': '대한민국',
     'short_name': 'KR',
     'types': ['country', 'political']},
    {'long_name': '110-126',
     'short_name': '110-126',
     'types': ['postal_code']}],
   'formatted_address': '대한민국 서울특별시 종로구 종로6가 종로 288',
   'geometry': {'location': {'lat': 37.5711389, 'lng': 127.0095452},
    'location_type': 'ROOFTOP',
    'viewport': {'northeast': {'lat': 37.5724878802915,
      'lng': 127.010

__(1)동대문역의 주소('대한민국 서울특별시 종로구 종로6가 종로 288')를 추출하여, long_addr 변수에 저장하세요.__

In [105]:
long_addr = json['results'][0]['formatted_address']
print(long_addr)

대한민국 서울특별시 종로구 종로6가 종로 288


__(2) 동대문역의 위도(37.5711389), 경도(127.0095452) 정보를 추출하여, lat, lng변수에 저장하세요.__

In [120]:
lat = json['results'][0]['geometry']['location']['lat']
lng = json['results'][0]['geometry']['location']['lng']

print(lat, lng)

37.5711389 127.0095452


* (참고) xml 형식의 데이터 처리
* XML 언어의 특징
- XML(eXtensible Markup Language): 데이터 저장 및 전달을 위해 만든 다목적 마크업 언어
- 태그를 이용해서 문서나 데이터를 구조화하는 언어
- HTML은 태그가 미리 정해져 있지만, XML은 자신이 태그를 정해서 사용 가능
- XML의 규칙
- 1. 태그는 <문자열>로 시작해서 </문자열>로 끝남(요소)
- 2. 태그를 중첩해서 사용할 때는 시작하는 순서와 끝나는 순서가 서로 일치해야 함
- 3. 태그의 속성은 <태그명 속성이름=＂속성값“>으로 표현함


In [ ]:
xml_data = """<?xml version="1.0" encoding="UTF-8" ?>
<사용자정보>
    <이름>홍길동</이름>
    <나이>25</나이>
    <거주지>서울</거주지>
    <신체정보>
        <키 unit="cm">175.4</키>
        <몸무게 unit="kg">71.2</몸무게>
    </신체정보>
    <취미>등산</취미>
    <취미>자전거타기</취미>
    <취미>독서</취미>
</사용자정보> 
"""
print(xml_data)

* XML형식의 데이터에서 데이터 추출하기: 파이썬 딕셔너리로 전환

In [123]:
import xmltodict

In [124]:
# !pip install xmltodict

You should consider upgrading via the 'C:\Users\SSAFY\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [126]:
import xmltodict
import json

dictionary = xmltodict.parse("""<note>
  <date>2021-03-07</date>
  <time>15:23</time>
  <to>Sara</to>
  <from>Khan</from>
  <msg>Let's meet this weekend!</msg>
</note>""")
json_object = json.dumps(dictionary) 
print(json_object)

{"note": {"date": "2021-03-07", "time": "15:23", "to": "Sara", "from": "Khan", "msg": "Let's meet this weekend!"}}


In [127]:
json.loads(json_object)

{'note': {'date': '2021-03-07',
  'time': '15:23',
  'to': 'Sara',
  'from': 'Khan',
  'msg': "Let's meet this weekend!"}}

 The first character is a blank
6
